# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df0e6b1ebd935a0bfe1ff7a5c85b965a6c1925007976f3e35377f90e37aa0192546f827784a5ca027a5d8df4a1f624a4218d7edaf27dadb3b08cc1a5e6a5888d

test:
  secret_key_base: 55a0c0f831167d503fb4a7fa19940e804f954838f0ff9f46358d2dec522fb1b030bf2dc7a36603e6e8ae6362b08a856014f0838b57e93641d82d770eeb34d69b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
