# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88fcb5976fadc42088ce2efe8bcd0ff735a62a8ec7fe39f7ab2b277e297373a7f3a01f734a528d61bbb75db51cd974097da0e7e4daa751f4513dc7cd188eb503

test:
  secret_key_base: 480eda82d430b3b460778be085667aee2fc668cefb54bfac15170cf94273d54b0d422c43ab33086d53fe372d27236f2e3406bef0afcf9aa0557b893404e0bb89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
